from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.transfers.gcs_to_bigquery import GCSToBigQueryOperator
from airflow.utils.dates import days_ago
import os
import sys

# Add scripts directory to path so we can import the ingestion script
sys.path.append(os.path.join(os.environ.get("AIRFLOW_HOME", "/opt/airflow"), "scripts"))

from ingest_kaggle_mental_health import ingest_kaggle_data

# Configuration
GCS_BUCKET_NAME = os.environ.get("GCS_BUCKET_NAME", "your-bucket-name")
PROJECT_ID = os.environ.get("GCP_PROJECT_ID", "your-project-id")
DATASET_ID = "raw_zone"
TABLE_ID = "mental_health"

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
}

with DAG(
    'kaggle_mental_health_ingestion',
    default_args=default_args,
    description='Ingest Mental Health dataset from Kaggle to BigQuery via GCS',
    schedule_interval='@weekly',
    start_date=days_ago(1),
    catchup=False,
    tags=['kaggle', 'ingestion', 'epic2'],
) as dag:

    ingest_task = PythonOperator(
        task_id='ingest_to_gcs',
        python_callable=ingest_kaggle_data,
        env={
            "GCS_BUCKET_NAME": GCS_BUCKET_NAME,
            # Ensure authentication env vars are passed if not handled by Airflow connections
            "KAGGLE_USERNAME": os.environ.get("KAGGLE_USERNAME"),
            "KAGGLE_KEY": os.environ.get("KAGGLE_KEY"),
        }
    )

    # Assuming we know the filename, or using a wildcard
    # The script uses {date_str} in the path. Airflow templates can help here if we want dynamic paths.
    # For simplicity, we'll try to load all CSVs from the latest date partition or similar.
    # Since the script uses the current date, we should probably align the GCS path with the execution date.
    
    # However, for this initial version, let's assume we want to load the file generated by the previous step.
    # We might need to adjust the script to return the path or use XCom, 
    # but the GCSToBigQueryOperator supports wildcards.
    
    load_to_bq = GCSToBigQueryOperator(
        task_id='gcs_to_bigquery',
        bucket=GCS_BUCKET_NAME,
        source_objects=[f"raw/mental_health/{{{{ ds }}}}/Mental Health Dataset.csv"], # We need to know the specific filename or use *.csv
        destination_project_dataset_table=f"{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}",
        source_format='CSV',
        write_disposition='WRITE_TRUNCATE', # Replace data for now, or APPEND for history
        autodetect=True,
        skip_leading_rows=1,
    )

    ingest_task >> load_to_bq
